sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
  - ADDON="smartthings"
script:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - ./build.sh $ADDON
